### ISSUE TITLE
Default spawn is on an island unable to get out

### ISSUE THREAD

**Issue by tsaber** [Oarcinae/FactorioScenarioMultiplayerSpawn#34] opened 2017-10-21 17:35 UTC
And no resources around. Does anyone know how to fix it?

**Comment by Oarcinae** [comment] 2017-10-27 15:16
Could you explain more about this? Did you figure out the issue?

**Comment by Oarcinae** [comment] 2017-11-08 13:40
Closing this as I don't know what @tsaber is referring to. If this is when you select the "moat" spawn option, this is intended and you can escape the island by building landfill. Also, spawning is random so you may spawn in the middle of a large body of water. This is intended behavior and you can landfill to escape.

**Closed by Oarcinae** 2017-11-08 13:40 UTC
