### ISSUE TITLE
Construction robot self destruction

### ISSUE THREAD

**Issue by bplein** [Oarcinae/FactorioScenarioMultiplayerSpawn#134] opened 2021-07-08 19:56 UTC
I am seeing construction robots self destruct if they are very busy traveling over long distances. 

I have grepped through this code and haven't seen anything specific to robots.

I have a few other mods in place, but none of them mention robots in their code either. 

Is there a way to turn on some LUA that would log entity destruction and maybe point to the code line and file that did it?

**Comment by lewisandrew** [comment] 2021-07-20 02:05
I encountered this also and mentioned it in the Discord server, but didn't look into it too far. I'm currently seeing similar bizarre behavior where long electric poles are getting deleted/destroyed out of the blue.
![image](https://user-images.githubusercontent.com/3252798/126251141-fbb8e7aa-8c74-4712-97f0-431cba554bda.png)

**Comment by lewisandrew** [comment] 2021-07-20 02:28
Turning that setting off didn't fix this related issue. I don't have bots traveling very far distances over water much anymore, but I think this maybe the same root cause
![image](https://user-images.githubusercontent.com/3252798/126252892-df3f784b-41fc-4833-807a-be6b6af8ec5c.png)

**Comment by bplein** [comment] 2021-07-20 17:15
I've had construction bots in my personal roboport self destruct too, but I can't swear if they were in or outside my direct "vision", i.e. mass deconstruct of a forest, I run in and run away and next thing you know,  bots are dying. 

Then again, I've had individual small groups of bots fly across a great map distance to catch up with me if I took a train and forgot to wait for them. 

For bots, it only seems to occur if there's a lot of them flying in one area.

**Comment by Oarcinae** [comment] 2021-07-22 00:19
Yeah this is definitely an odd one... We discussed on discord but I have no idea what I could be doing in my scenario. This might be worth reporting on the official factorio forum for help. This might be something obscure where my chunk deletion caused robot pathing to fail and subsequently to self destruct or some weird unknown side effect like that... I don't have time to look into this myself and haven't been touching the scenario or the game for quite awhile now, please let me know if you find something that I can do to help fix this.

**Comment by bplein** [comment] 2021-07-22 03:25
I've reported it there and basically they want me to test removing every mod one at a time. 

I actually find it sort of cool. 

Tired bots trudge on. But if you overexcite a bunch of them to the point of exhaustion, they expire and die. 

Sort of like working animals and humans. 

Not a big deal actually. But if you had some way to log items destroyed by your map reclamation or some other hints at LUA I could add to log things, id be happy to try it. 

Cheers.

**Comment by lewisandrew** [comment] 2021-07-23 04:04
I commented out all the regrowth related code being called outside of the regrowth_map.lua. Couple hours of playing and I haven't seen the issue again yet. Will update again in the future if I see it happen

**Comment by vfinn** [comment] 2022-01-24 03:12
Any update on this ?
I'm working on a mod that removes the player - merging "Brave New World" with Oarc. This means you MUST use bots, you start with 100 construction, and 50 logistic. Since power is the first thing to get the bots need to work pretty hard at the start, and it is likely you will run out of power. I've had 88 of the starting 100 construction bots self destruct going on low power to remove trees on the perimeter. The base is increased from normal 32 CHUNK_SIZE to 48. This will be the thing that keeps me from proceeding with this
![Factorio bots dieing](https://user-images.githubusercontent.com/2693989/150716128-99e1625d-e6d4-443c-b496-9de43fd563fb.png)
.

**Comment by vfinn** [comment] 2022-01-24 03:17
I noticed this in config:
-- Cleans up unused chunks periodically. Helps keep map size down.
ENABLE_REGROWTH = true

I'll set this to false and see what happens...

**Comment by vfinn** [comment] 2023-01-09 17:13
A fix for this was submitted today into [vfinn/FactorioScenarioMultiplayerSpawn](https://github.com/vfinn/FactorioScenarioMultiplayerSpawn) branch. If anyone would like to test merge:
oarc_utils.lua and regrowth_map.lua into your game save or mod for a new game.  Run the bots across a large span away from main base to build - say a long wall, or defenses. When the bots run out of energy they should just slow to 20% speed. If a regrowth occurred while they are travelling long distance they would previously explode in groups. This fix keeps them from exploding.
 
JustGoFly

**Comment by William071802** [comment] 2024-03-18 22:24
> A fix for this was submitted today into [vfinn/FactorioScenarioMultiplayerSpawn](https://github.com/vfinn/FactorioScenarioMultiplayerSpawn) branch. If anyone would like to test merge: oarc_utils.lua and regrowth_map.lua into your game save or mod for a new game. Run the bots across a large span away from main base to build - say a long wall, or defenses. When the bots run out of energy they should just slow to 20% speed. If a regrowth occurred while they are travelling long distance they would previously explode in groups. This fix keeps them from exploding.
> 
> JustGoFly

If you've confirmed this fixes it you should probably make a pull request so @Oarcinae sees it. Would be awesome to see this old bug finally squashed.

**Comment by Oarcinae** [comment] 2024-08-07 19:25
Going to close this since it seems to have been fixed :)
Thanks JustGoFly!

**Closed by Oarcinae** 2024-08-07 19:25 UTC
