### ISSUE TITLE
Add a "restart" option

### ISSUE THREAD

**Issue by Eddoson** [Oarcinae/FactorioScenarioMultiplayerSpawn#50] opened 2018-10-30 01:01 UTC
I'm not sure if this option already exists but if not it would be great to have it.

I'm in a situation where I didn't realize that how hard far spawns are due to biters being so dense and tough. I've passed the 15 minute mark so I can't just leave and have the server erase my character for me. I'm wondering if there's code already written to delete characters and spawns if there would be a way to run that script manually at any time? Sort of like a hard restart button where it erases everything you own and your character and it's like you're entering the server for the very first time?

**Comment by Oarcinae** [comment] 2019-02-21 14:42
Hi, I'm surprised I didn't respond to this earlier, must have missed the notification.

Deleting after a longer period of time is possible, but a little more difficult since it's likely that more chunks have been generated. It's possible to reset a person, but it's likely their base would have to remain. I'll look into this for the next update to this scenario (when 0.17 releases I will work on it again).

**Comment by davv1** [comment] 2019-03-15 17:08
Hello. Could I get instructions on how to manually remove player, so he can start one more time, and change his settings? I assume, it's not possible to DISABLE shared research, or it is?

**Comment by Oarcinae** [comment] 2019-03-15 19:52
@davv1 The quick hacky way is to type in the command line something like this:
`/c DisplayWelcomeTextGui(game.player["player_name"])`

The better way will be in the next change I add, under the admin panel there will be a "Reset Player" button next to the "Ban" button. So it will be much easier to restart a player, but still limited to admin control.

I'm not sure what you mean about disabling shared research. The way research works is that each force has their own research. If you want different research trees, just go onto different teams. That's what the `Create Your Own Team (own research tree)` option is for.

**Comment by Oarcinae** [comment] 2019-03-15 19:59
Just pushed the change, give it a try if you can:
![image](https://user-images.githubusercontent.com/23324249/54458845-5b2f9b80-473b-11e9-8f84-eb96e274cc27.png)

**Comment by Oarcinae** [comment] 2019-03-15 20:00
If this works for anyone else, I'll close out this feature request.

**Comment by davv1** [comment] 2019-03-16 01:26
I'll test when my friend is online, thanks for your support.

**Comment by davv1** [comment] 2019-03-16 01:27
BTW how can I push change to already started save?

**Comment by Oarcinae** [comment] 2019-03-16 03:28
@davv1 Unfortunately there is not a good way to do that. You could attempt to unzip the save and modify files manually but it's also likely you'll just corrupt the save or crash the game.

Best recommendation is to just keep playing your current version until you're done, or restart if the changes seem worth it.

This is still in development so expect frequent updates.

**Comment by davv1** [comment] 2019-03-16 07:25
Works as intended. Got START screen after restarting my player. Could choose, and of course, make spawn which I chosen. I can provide updated save with patched scenario.

Basically, I just opened save with WinRAR, and dragged new scenario files into WinRAR, and confirmed .zip archive settings, then started game. Of course it was done on backup save, so when something will break, I can return to previous save. :)

Very big thanks for your support :+1:

**Comment by davv1** [comment] 2019-03-16 07:28
And there's bonus for you. :D

**Comment by Oarcinae** [comment] 2019-03-16 12:52
Excellent, I'll close this feature request then. I'll take a look at the hover-over issue as well.

**Closed by Oarcinae** 2019-03-16 12:52 UTC
Labels: enhancement
