### ISSUE TITLE
Scenario crashes on load

### ISSUE THREAD

**Issue by sapid** [Oarcinae/FactorioScenarioMultiplayerSpawn#31] opened 2017-08-22 10:36 UTC
Used default presets; no mods apart from the scenario. Config is modified: disabled long reach, undecorator, regrowth.

Crash log is [here](https://gist.github.com/sapid/3e21fa5a2e31428974fecadba37bba24)

**Comment by sapid** [comment] 2017-08-23 09:25
After more research, it seems like this bug may be on Factorio's end, not yours. The only similar bug I could find was in a [post](https://forums.factorio.com/viewtopic.php?f=94&t=21568&p=296953&hilit=water+maze#p296953) about another scenario fairly recently. Either way, I can't for the life of me figure out why Factorio is rejecting the require ONLY for `separate_spawns_guis.lua`

I worked around it by turning this scenario in to a mod. (Turned out to be easier than I expected!)

This revealed a new problem, though - if a player chooses default spawn, they don't get teleported out of the lobby moat. Is this a known issue?

I noticed your lobby surface code, so I worked around this by turning that code on, spawning the player on the lobby surface, then teleporting them to the default spawn if that's the spawn they choose.

**Comment by Oarcinae** [comment] 2017-08-25 18:11
I bet I messed up something when those options are disabled. Shouldn't be hard to fix, I'll look into it when I get time. Thanks for reporting it!

**Comment by sapid** [comment] 2017-08-26 17:27
If it's any help, I've uploaded almost all of the changes I made over here:
https://github.com/sapid/FactorioScenarioMultiplayerSpawn/tree/mod-0.15.x

However, it's a work in progress; not everything that should be moved to settings.lua has been moved there.

**Comment by Oarcinae** [comment] 2017-08-26 20:32
Yeah, to be honest I've let a lot of the original code go untested in my recent push. I currently don't have time to do any testing of a lot of the configuration options. The issues you're seeing are most likely because I added regrowth and did not test the all the options that are in the config... Thanks for sharing your code.

Whenever I do get time to look into it, I'll eventually try to clean up some of it.

**Comment by Oarcinae** [comment] 2017-11-08 13:49
I'm restesting now with the same things disabled (long reach, undecorator, regrowth) but I am not crashing on load. Closing this issue as I can't reproduce with the latest version. Please re-open or make a new one if this is still an issue. I'm also making sure everything works even when regrowth is disabled.

**Closed by Oarcinae** 2017-11-08 13:49 UTC
