### ISSUE TITLE
0.16.X issues

### ISSUE THREAD

**Issue by AusKarlos** [Oarcinae/FactorioScenarioMultiplayerSpawn#40] opened 2017-12-16 12:57 UTC
Ive been using your awesome script for 0.15 for a public server and has been working great. But obviously things are broken in 0.16.X.

Here are a few ive noted.
oarc_utils.lua
Line 750, 781, 818, 1050 change grass to grass-1

Line 522 use scrollFrame.can_scroll_horizontally = false (I think, it works on client hosted but seems to bug out on headless servers).

separate_spawns_guis.lua
Line 414, 523 same thing need to swap out scroll_horizontal_policy = "never" to  can_scroll_horizontally = false (Again seems to work fine on client hosted sessions but bugs out and can crash headless servers)

Theres also a current bug i cant pin down and that is sometimes new people arn't able to interact with the Welcome GUI to create or join a team.

I also havent figured out how to remove cliffs from the spawn area. My best attempts either leave the cliffs in or get an exception. However 0.16.4 has just been released with new lua function to remove cliffs.
"Added 2 optional parameters to LuaSurface::create_entity when creating resource entities: enable_tree_removal and enable_cliff_removal"

Also with the new water/edge tiles your little water strip no longer works. Need to add width to the strip now.

Hope this helps somewhat.

**Comment by Oarcinae** [comment] 2017-12-16 13:08
Hey, I have a 0.16 dev branch, give that a try. I fixed all the issues you listed except I don't know what might cause the GUI bug where sometimes people can't interact with the menu... that one I haven't seen yet.

Try it here: https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/tree/dev_0.16

It has a LOT of changes to the config settings, so you may want to tweak them. It also has no RSO soft mod just yet.

Were you able to get the RSO portion of it working at all by the way?

**Comment by Oarcinae** [comment] 2017-12-16 13:18
Any other 0.16 issues can be posted here as well.

**Comment by AusKarlos** [comment] 2017-12-16 13:25
Hi, yeah i literately just saw the dev branch and facepalmed.
Ive actually always had RSO disabled as the latest iterations in 0.15 have implemented a better ore spawning for vanilla and the ores did indeed get richer the further you traveled.

I'll keep testing.. I have enabled the RSO option in your config but im unsure if its loading or not. Is it just as simple to re-add Enable_rso = true to the config or is there more involved.

**Comment by AusKarlos** [comment] 2017-12-16 15:16
Might as well post it in here.
For a feature request could you change how open spawns work. Instead of allowing anyone to join an open spawn they request an invite on a 30sec timer. This way it will stop random people joining a team if the owner of the team is not online, had this a couple of times where the team host crashed and he's spawn was left open after inviting a friend to join him, he then came back to find a random player had also joined his spawn.

**Comment by Oarcinae** [comment] 2017-12-16 21:06
I'm working on RSO. The latest dev branch should have my RSO soft mod in it and possibly working :)

Regarding the open spawns, I'll add that as a separate request. It's a good idea, but takes time to make sure the GUI options work correctly and without bugs.

**Comment by AusKarlos** [comment] 2017-12-17 02:37
Can still confirm with the dev build the GUI does not work at all now. The buttons will display, but nothing happens if you click on them. New players are unable to join.
This is on a Headless Server Linux running 0.16.4
The scenario files run fine on a client hosted game in Windows.
Do you have a debug function in the config file to enable some kind of verbose logging of gui interaction. 
Nothing turns up in the server logs so it will be hard to track down why its not working.

**Comment by Cyberzoid1** [comment] 2017-12-17 03:44
I'm running this on 16.2 and its working for me. Try downgrading and give it a shot

**Comment by Oarcinae** [comment] 2017-12-17 05:38
I'm running on 16.4 headless Linux. Friend and I had no problems joining but I have tested all the spawn menu options

**Comment by Oarcinae** [comment] 2017-12-17 05:39
*have not tested all options*

**Comment by Oarcinae** [comment] 2017-12-17 05:40
Are you running any other mods?

**Comment by AusKarlos** [comment] 2017-12-17 08:06
Nope vanilla only.
 It might be because im repacking the zip file of a save with the 0.16 scenario inside, deleting the server created /factorio/scenario folder and the /factorio/temp folder before booting the server back up.

**Comment by Noa3** [comment] 2017-12-17 08:07
0.16.4 i have the same problem with the gui, and if anyone want to join, the server shelf crashes and shoutdown.

My way to create a Server: Download Scenario > Start Factorio > Load Scenario Oarc_0.16 > generate a map > save(without clicking on GUI) > place save on server > let server start and load the save > join > GUI and crash bug

i have even no mods besides running

**Comment by Oarcinae** [comment] 2017-12-17 14:24
Excellent. There is probably something about the process of saving the zip in windows and then using it on Linux that is breaking with 0.16. I'll see if there's anything I can do in my code but that sounds like a real game bug.

Here is my process and it's probably reason I have no problems. I don't save the zip from my pc, I start the game and map from the command line and have the scenario located in the scenarios folder.


THIS IS MY "start-server.sh" linux script:
```
#!/bin/bash

factorio_exe="/mnt/ssd/factorio_0.16/bin/x64/factorio"
settings_files="--server-settings my-server-settings.json --server-banlist banlist.json"
log_file="--console-log my-server.log"

start_scenario_cmd="--start-server-load-scenario FactorioScenarioMultiplayerSpawn"

$factorio_exe $start_scenario_cmd $settings_files $rcon_settings $log_file
```


My scenario code is located in ../factorio_0.16/scenarios/FactorioScenarioMultiplayerSpawn.

**Comment by AusKarlos** [comment] 2017-12-17 14:41
I'll try --start-server-load-scenario.
When the server loads a zip map it automatically extracts the scenario files. But maybe forcing the scenario to start first before the server loads the map could work. I'll check it out. The only other possibility is that its possible factorio bakes some part of the scenario into the level.dat.

**Comment by Noa3** [comment] 2017-12-17 15:51
THX, i will try it later.

one more thing if i join a server with oark and just save(in windows) the map on my pc, upload this again on the server, the same problems come up.

**Comment by Oarcinae** [comment] 2017-12-17 16:44
So I'm currently hosting a game on my linux server so I can't test this out, but it really does sound like a game issue since it works one way and not the other.

@AusKarlos I'm not familiar with the Linux service, but you could edit the ExecStart line right? I assume that's just a file somewhere you can edit? Since the service looks like it loads the latest save, you should just "manually" start a game without the service by running --start-server-load-scenario first. You should then be able to stop the game and resume it with the service I think?

And yes, I believe there IS a level.dat file when you save the zip. A save is different than just the "pure" scenario because it includes the generated level and the map settings. However, I did implement the scenario in a way that makes it convenient to start from the command line hopefully.

**Comment by Noa3** [comment] 2017-12-17 19:08
sometimes if someone join, i get a server crash with this error message:

```
2017-12-17 19:41:54 [JOIN] APKAXEH joined the game
3331.014 Error MainLoop.cpp:1013: Exception at tick 197033: Error while running event level::on_gui_click (ID 1)
...verfiles/temp/currently-playing/separate_spawns_guis.lua:528: attempt to index local 'player' (a nil value)
3331.015 Error ServerMultiplayerManager.cpp:95: MultiplayerManager failed: "Error while running event level::on_gui_click (ID 1)
...verfiles/temp/currently-playing/separate_spawns_guis.lua:528: attempt to index local 'player' (a nil value)"
3331.015 Info ServerMultiplayerManager.cpp:693: mapTick(197033) changing state from(InGame) to(Failed)
3331.015 Info GlobalContext.cpp:660: Waiting for child processes to exit: 
```

maybe it can help to fix some things

**Comment by Oarcinae** [comment] 2017-12-17 19:47
@Noa3 I pushed a tentative patch for that error. I'm not sure how that function is receiving an invalid player parameter though so I don't know the root cause.

**Comment by AusKarlos** [comment] 2017-12-17 23:39
@Oarcinae The service is similar to how a bash script runs, but you can assign a user (that doesn't have the ability to log in and restricts executions) to exec the server. This can reduce the risk of someone attempting to run a bash script through the factorio server.

Ive edited the ExecStart line as followed
ExecStart=/home/Factorio/bin/x64/factorio --start-server-load-scenario FactorioMPSpawn --server-settings server-settings.json --server-banlist banlist.json
(The server loads a new map but the scenario does not start, files are in the correct location, but also creates a save file with the scenario files inside which indicates it did find the scenario folder)

ExecStart=/home/Factorio/bin/x64/factorio --start-server-load-scenario /home/Factorio/Scenarios/FactorioMPSpawn/  --server-settings server-settings.json --server-banlist banlist.json
(Throws an error at startup about an incorrect path.)

**Comment by Noa3** [comment] 2017-12-18 01:00
@AusKarlos try /home/Factorio/bin/x64/factorio --start-server-load-scenario FactorioMPSpawn --server-settings server-settings.json --server-banlist banlist.json

**Comment by AusKarlos** [comment] 2017-12-18 01:43
After some more testing and hex editing I have found that Factorio does indeed store part of the scenario in the level-init.dat and the level.dat. I have no clue how to edit it so im not going to attempt it.

**Comment by Oarcinae** [comment] 2017-12-18 01:59
Are you using some hosted server where you don't have full access? I would try not using the Linux service method and trying to just launch the executable directly like how Noa3 recommended. Depending how that goes, we can then better help debug.

**Comment by AusKarlos** [comment] 2017-12-18 02:28
Phew... Got it to work. It was a combination of starting a new map with the scenario and coping the level.dat + level-init.dat + script.dat from my current server map to this new map zip file. 
I also completely wiped the server directory. There must be some hidden files or something. But the scenario and all the GUI work with the converted map from 0.15.40 to 0.16.5

**Comment by Noa3** [comment] 2017-12-18 07:38
i got a crash again after a player joined:

```
`2017-12-18 08:32:34 [JOIN] theogil joined the game
5985.928 Error MainLoop.cpp:1013: Exception at tick 2904711: Error while running event level::on_gui_click (ID 1)
...r/serverfiles/temp/currently-playing/separate_spawns.lua:227: attempt to index local 'player' (a nil value)
5985.928 Error ServerMultiplayerManager.cpp:95: MultiplayerManager failed: "Error while running event level::on_gui_click (ID 1)
...r/serverfiles/temp/currently-playing/separate_spawns.lua:227: attempt to index local 'player' (a nil value)"
5985.928 Info ServerMultiplayerManager.cpp:693: mapTick(2904711) changing state from(InGame) to(Failed)
5985.929 Info GlobalContext.cpp:661: Waiting for child processes to exit: 
5986.584 Info ServerMultiplayerManager.cpp:141: Quitting multiplayer connection.
5986.584 Info ServerMultiplayerManager.cpp:693: mapTick(4294967295) changing state from(Failed) to(Closed)
5986.586 Info HttpSharedState.cpp:54: Downloading https://multiplayer.factorio.com/remove-game/509794
5986.692 Info HttpSharedState.cpp:127: Status code: 200
5986.726 Info UDPSocket.cpp:206: Closing socket
5986.727 Info UDPSocket.cpp:236: Socket closed`
```

**Comment by Oarcinae** [comment] 2017-12-18 17:33
It feels like somehow some GUI click events are receiving an invalid player index... I'm adding in catches for invalid "players" in all the gui related functions.

**Comment by Oarcinae** [comment] 2017-12-18 17:35
@AusKarlos I was confused as to what you were trying to do. I missed the part where you said you were repacking the zip file of an older save. Yeah, I'm not surprised you ran into so many issues. I highly recommend starting a new save since there could be potential for bugs later down the road. But I understand wanting to save your progress on a map :) I'm glad you got it working!

**Comment by Oarcinae** [comment] 2017-12-18 17:37
@Noa3 I just pushed another attempt at catching all cases where a gui event doesn't have a valid player.

**Comment by Spencer-Dawson** [comment] 2017-12-29 23:36
![oarc_player_list_crash](https://user-images.githubusercontent.com/1687388/34449510-2dd15ae2-ecb6-11e7-8be4-66d7a05a84ed.JPG)
Any idea why clicking on the Player List is triggering crashes in 0.16.7 ?

**Comment by Noa3** [comment] 2017-12-30 10:46
i think you use a old version. update the mod and try again

**Comment by Spencer-Dawson** [comment] 2017-12-30 20:49
Doh! That was the issue. (I had that commit from a few days ago that Oarcinae reverted)

**Comment by bplein** [comment] 2018-01-12 20:50
@Oarcinae Thanks for providing this scenario as open source.

I was trying to get dev_0.16 working with 16.16 and am running into issues, both with GUI (macOS) as well as headless Linux.

GUI MacOS:
I clones the repo into the scenarios directory, and then edited config.lua to change only the text of the first server message and also to set "SERVER_OWNER_IS_OARC = false" and REM out the next two lines.

On startup, I choose the scenario. At the Map Generator screen I change nothing and hit "Generate"
Multiplayer Lobby comes up, changed the name (no special character) and hit Play. 

Then I get a Notice box with the error (also in factorio-current.log):
`Error while running event level::on_chunk_generated (ID 12)
Unknown tile name: grass
stack traceback:
	...rt/factorio/temp/currently-playing/locale/oarc_utils.lua:1065: in function 'CreateHoldingPen'
	...rt/factorio/temp/currently-playing/locale/oarc_utils.lua:1071: in function 'CreateHoldingPenGenerateChunk'
	...tion Support/factorio/temp/currently-playing/control.lua:177: in function <...tion Support/factorio/temp/currently-playing/control.lua:155>`

Similar results using Linux headless:

Start the headless with your recommended startup for automatic map generation. When I connect to it (public server), I get "server not responding" and the following is in the server logs:
`77.186 ConnectionRequestReplyConfirm (type(ConnectionRequestReplyConfirm) ) from(104.14.158.108:6888)
  77.186 Info ServerRouter.cpp:393: Replying to connectionRequest for address(104.14.158.108:6888).
  77.186 Info ServerSynchronizer.cpp:557: nextHeartbeatSequenceNumber(2030) adding peer(1)
  77.204 Info ServerMultiplayerManager.cpp:696: mapTick(0) changing state from(InGame) to(InGameSavingMap)
  77.259 Info ServerMultiplayerManager.cpp:792: mapTick(0) received stateChanged peerID(1) oldState(Ready) newState(ConnectedWaitingForMap)
  77.369 Info ServerMultiplayerManager.cpp:852: MapTick(0) Serving map(/opt/factorio/temp/mp-save-0.zip) for peer(1) size(728863) crc(1302040617)
  77.370 Info ServerMultiplayerManager.cpp:696: mapTick(0) changing state from(InGameSavingMap) to(InGame)
  77.477 Info ServerMultiplayerManager.cpp:792: mapTick(0) received stateChanged peerID(1) oldState(ConnectedWaitingForMap) newState(ConnectedDownloadingMap)
  77.494 Warning TransmissionControlHelper.cpp:172: Fragment 0001 failed too many times
  77.529 Warning TransmissionControlHelper.cpp:172: Fragment 0002 failed too many times
  77.529 Warning TransmissionControlHelper.cpp:172: Fragment 10002 failed too many times
  77.529 Warning TransmissionControlHelper.cpp:172: Fragment 20002 failed too many times
  77.529 Warning TransmissionControlHelper.cpp:172: Fragment 30002 failed too many times
  77.867 Info ServerMultiplayerManager.cpp:792: mapTick(0) received stateChanged peerID(1) oldState(ConnectedDownloadingMap) newState(ConnectedLoadingMap)
  77.891 Error MainLoop.cpp:1013: Exception at tick 0: Error while running event level::on_chunk_generated (ID 12)
The result of this function must be used.
stack traceback:
/opt/factorio/temp/currently-playing/locale/rso/drand.lua:244: in function 'random'
...ctorio/temp/currently-playing/locale/rso/rso_control.lua:1146: in function 'roll_region'
...ctorio/temp/currently-playing/locale/rso/rso_control.lua:1404: in function 'RSO_ChunkGenerated'
/opt/factorio/temp/currently-playing/control.lua:165: in function </opt/factorio/temp/currently-playing/control.lua:155
  77.891 Error ServerMultiplayerManager.cpp:95: MultiplayerManager failed: "Error while running event level::on_chunk_generated (ID 12)
The result of this function must be used.
stack traceback:
/opt/factorio/temp/currently-playing/locale/rso/drand.lua:244: in function 'random'
...ctorio/temp/currently-playing/locale/rso/rso_control.lua:1146: in function 'roll_region'
...ctorio/temp/currently-playing/locale/rso/rso_control.lua:1404: in function 'RSO_ChunkGenerated'
/opt/factorio/temp/currently-playing/control.lua:165: in function </opt/factorio/temp/currently-playing/control.lua:155>"
  77.891 Info ServerMultiplayerManager.cpp:696: mapTick(0) changing state from(InGame) to(Failed)
  77.891 Info GlobalContext.cpp:671: Waiting for child processes to exit: 
  78.175 Info ServerMultiplayerManager.cpp:141: Quitting multiplayer connection.
  78.175 Info ServerMultiplayerManager.cpp:696: mapTick(4294967295) changing state from(Failed) to(Closed)
  78.175 Info HttpSharedState.cpp:54: Downloading https://multiplayer.factorio.com/remove-game/807956
  78.212 Info HttpSharedState.cpp:127: Status code: 200
  78.212 Info UDPSocket.cpp:206: Closing socket
  78.212 Info UDPSocket.cpp:236: Socket closed
`

**Comment by Oarcinae** [comment] 2018-01-12 21:23
@bplein It looks like you are using an older version of the scenario? Did you just download it now or awhile ago? The issue with the "grass tile" was fixed awhile ago (I'm currently running my scenario on 16.16 as well). The errors being printed out don't match the line numbers of the scenario code in the latest version I think Can you please confirm?

Also, how are you generating the map to host on the headless server? I have heard the generating on another PC using the game menu and then copying that save to the server results in failures. On linux you should create a new map from the command line as explained above.

Check and let me know, I can help get it working!

**Comment by bplein** [comment] 2018-01-12 21:27
Thanks for the quick response. 

I did a git clone of the dev_0.16 today. But let me retry it just so I don't send you on a wild goose chase. 

On the headless, I was using using the "Option 3" to generate, i.e. running:
`./factorio --start-server-load-scenario FactorioScenarioMultiplayerSpawn --server-settings my-server-settings.json`

**Comment by Spencer-Dawson** [comment] 2018-01-12 21:28
"how are you generating the map to host on the headless server" Obviously I am not bplein, but I've had no issues copying over a map saved from windows onto my Linux server. I have been doing just that on roughly a bi weekly basis for the past two weeks, but that is just my experience on that issue.

**Comment by bplein** [comment] 2018-01-12 21:28
Doh! I just cloned it, didn't update to the dev_01.16 branch. Will do it right and report back.

**Comment by Oarcinae** [comment] 2018-01-12 21:29
@Spencer-Dawson Thanks for that info! That's good to know.
@bplein No worries, give it a go and let me know. dev 16 is still kind of dev so I wouldn't be surprised if you run into different issues.

**Comment by bplein** [comment] 2018-01-12 21:34
OK, that was the issue. I use git clone ALL the time but I'm not a developer so I forgot to pick up the branch (I was git cloning the original after copy/paste from the tool on the page). 

Great scenario, will continue testing it.

**Comment by bplein** [comment] 2018-03-11 15:48
Something seems to have changed where when you join the server, the GUI text is all smashed up. Since you didn't change the code, it must be something that's changed in Factorio in the last 2 months or so? I haven't used OARC scenarios since January. 
<img width="613" alt="screenshot 2018-03-10 17 58 01" src="https://user-images.githubusercontent.com/260078/37255382-bc447f84-2519-11e8-8157-f695a1c3da1b.png">
<img width="594" alt="screenshot 2018-03-10 17 58 14" src="https://user-images.githubusercontent.com/260078/37255384-c2463422-2519-11e8-9f90-d0f46ed2436f.png">

**Comment by Oarcinae** [comment] 2018-03-15 22:01
@bplein This should now be fixed in the latest version, but now all the text is spread far apart :(

**Comment by bplein** [comment] 2018-03-16 23:02
Thanks I'll check it out. Still dev_0.16 correct?

**Comment by bplein** [comment] 2018-03-16 23:25
Still bad message graphics, and fails with error.

I did a clean git clone. Then git checkout dev_0.16. Then fired up factorio with this scenario:

<img width="692" alt="screenshot 2018-03-16 18 24 00" src="https://user-images.githubusercontent.com/260078/37548657-689950da-2947-11e8-86a7-02b1214597b6.png">

**Comment by Oarcinae** [comment] 2018-03-16 23:35
@bplein If you look at the current source, there is no /locale/rso/drand.lua file in the dev_0.16 branch. So I suspect you didn't checkout or clone correctly. Or pull maybe if you have an old version?

Also, just pushed another updated to improve text stuff.

**Comment by bplein** [comment] 2018-03-17 04:38
Thanks, my mistake. I was renaming directories (mv) and was testing the wrong one. I'm good to go for now! Thank you for all the hard work.

**Comment by Oarcinae** [comment] 2018-03-17 16:15
@bplein No problem, keep me updated if you find any issues or have any suggestions.

**Comment by Oarcinae** [comment] 2018-03-30 20:33
Closing this since 0.16 is stable and I haven't had any major issues while playing my scenario for the past 100+ hours. Any new issues should be created as specific issues now.

**Closed by Oarcinae** 2018-03-30 20:33 UTC
Labels: bug, help wanted
