### ISSUE TITLE
Server crashes after adding any helmod or recipe browsing mod

### ISSUE THREAD

**Issue by 15217444hch** [Oarcinae/FactorioScenarioMultiplayerSpawn#139] opened 2022-09-09 13:28 UTC
In single playing,there is no problem.But when I put it in to a server,the game always crashes as soon as someone joins it.How can I solve the problem?

**Comment by Oarcinae** [comment] 2022-09-12 15:15
@15217444hch I'm not sure I'll be able to solve that for you. Can you provide a screenshot of the error please?

**Comment by Oarcinae** [comment] 2024-09-14 23:05
I'm going to assume it's a duplicate of this issue: https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/issues/140

**Closed** 2024-09-25 17:15 UTC
